### ISSUE TITLE
nastavit vychozi vystup

### ISSUE THREAD

**Issue by landam** [ctu-fgis/2021-c-qgis-ruain-plugin#2]
Po otevreni pluginu se nastavit vystup automaticky na

```
GPKG $HOME/ruian.gpkg (C:\users\martin\ruian.gpkg)
```

**Comment by landam** [comment]
Dva widgety:

* ponechat comboxbox (driver) 
* odstranit textove pole
* pridat qgsfilewidget

Kdy zmenim format -> nastavit vlastnost qgsfilewidget ( `QgsFileWidget.setStorageMode(QgsFileWidget.SaveFile)` -  soubor vs adresar) - provadi `set_datasource`

Nove funkce, ktera bude napojena na qgsfilewidget

**Comment by landam** [comment]
- [x] click on `...`, cancel -> keep gpkg as default

**Comment by landam** [comment]
- [x] `Vystup comboxbox qlineedit(expand) pushbutton`

**Comment by vajner85** [comment]
Funkčnost změny prostředí u formátů GPKG a SQL je 100%. Formátu Esri shapefile u testování před dvěma týdny fungoval taktéž 100%. Den před prezentací však začal občas shazovat celou aplikaci. Vzhledem k neprovedení žádné změny a k tomu, že při spadnutí a následném testování nefungoval ani původní plugin před reworkem usuzuji, že se nejedná o chybu z naší strany.

**Comment by landam** [comment]
Pad aplikace jsem neznamenal. Po zmene formatu by se ale mela smazat nastavena cesta.

1. Zvolim cestu pro vystupni GPKG
2. Zmeni format na SQLite/SHP
3. Puvodne nastavena cesta zustava

@vajner85 Ocekavane chovani. Po zmene formatu dojde k vymazani posledne nastavene cesty.

**Comment by vajner85** [comment]
Provedl jsem lehkou změnu, kdy po změně formátu se smaže nastavená cesta a musí se zvolit znova.
