### ISSUE TITLE
pridat podporu pro UKSG

### ISSUE THREAD

**Issue by landam** [ctu-fgis/2021-c-qgis-ruain-plugin#3]
Vyber z udaju: zakladni + generalizovane hranice

![Screenshot from 2021-04-07 17-19-24](https://user-images.githubusercontent.com/5683186/113891569-77d91900-97c5-11eb-8582-c8a4f4ea0824.png)

**Comment by landam** [comment]
obce (ob) -> UKSH (originalni)
vusc (st) -> UKSH (originalni, nejsou vsechny vrtsvy)
vusc (st) -> USKG (generalizovane, vsechny vrstvy)

**Comment by landam** [comment]
`Vyber z udaju (VUSC):`

**Comment by landam** [comment]
> obce (ob) -> UKSH (originalni)
> vusc (st) -> UKSH (originalni, nejsou vsechny vrtsvy)
> vusc (st) -> USKG (generalizovane, vsechny vrstvy)

Podle zmen (https://github.com/ctu-fgis/2021-c-qgis-ruain-plugin/pull/6/files) to nevypada, ze byste tuto logiku implementovali (?)

**Comment by klicksab** [comment]
Byla přidána možnost základní + generalizované hranice do pokročilého nastavení a pro jednodušší výběr bylo doplněno, že se jedná o výběr z VUSC
